# Generated by Django 5.0.6 on 2026-06-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="district",
            unique_together={("state", "name")},
        ),
    ]
